#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Autostart application
xrandr --output Virtual1 --mode 1920x1080 &
#xrandr --output DP-0 --primary --mode 1920x1080 --pos 1920x0 --rotate normal --output DP-1 --off --output DP-2 --mode 1920x1080 --pos 0x0 --rotate normal --output DP-3  --off --output HDMI-0 --off --output DP-5 --off &
picom --config $HOME/.config/picom.conf &
nitrogen --restore &
dunst &
polybar &
